### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by cugu**

### CODE REVIEW

**Comment by cherue** [comment]
This only needs consent from @arekbulski.

@arekbulski do you approve of this license?

**Comment by arekbulski** [comment]
I am no longer a maintainer here on Kaitai. Anyway, you may publish whatever little I contributed under any, however ridiculous, license you think of. GNU or otherwise.

**Comment by cherue** [comment]
@GreyCat this can be merged now.

**Comment by arekbulski** [comment]
Okay, maybe not ANY license. Lets not get ridiculous. ^^. GNU or MIT will suffice. Same goes in the other thread.

**Comment by GreyCat** [comment]
Thanks, everyone!

**Pull request merged**
